services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app
    command:
      - node
      - dist/main.js
    environment:
      NODE_ENV: production
      PORT: 4000
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: 1d
    restart: unless-stopped
    container_name: backend-kw8oo4kk80so8080o0g0cgcw-121421733338
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.373
      - coolify.applicationId=27
      - coolify.type=application
      - coolify.name=backend-kw8oo4kk80so8080o0g0cgcw-121421733338
      - coolify.pullRequestId=0
      - traefik.enable=true
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.http-0-kw8oo4kk80so8080o0g0cgcw-backend.entryPoints=http
      - traefik.http.routers.http-0-kw8oo4kk80so8080o0g0cgcw-backend.middlewares=redirect-to-https
      - 'traefik.http.routers.http-0-kw8oo4kk80so8080o0g0cgcw-backend.rule=Host(`backend.henkify.org`) && PathPrefix(`/`)'
      - traefik.http.routers.https-0-kw8oo4kk80so8080o0g0cgcw-backend.entryPoints=https
      - traefik.http.routers.https-0-kw8oo4kk80so8080o0g0cgcw-backend.middlewares=gzip
      - 'traefik.http.routers.https-0-kw8oo4kk80so8080o0g0cgcw-backend.rule=Host(`backend.henkify.org`) && PathPrefix(`/`)'
      - traefik.http.routers.https-0-kw8oo4kk80so8080o0g0cgcw-backend.tls.certresolver=letsencrypt
      - traefik.http.routers.https-0-kw8oo4kk80so8080o0g0cgcw-backend.tls=true
      - 'caddy_0.encode=zstd gzip'
      - 'caddy_0.handle_path.0_reverse_proxy={{upstreams}}'
      - 'caddy_0.handle_path=/*'
      - caddy_0.header=-Server
      - 'caddy_0.try_files={path} /index.html /index.php'
      - 'caddy_0=https://backend.henkify.org'
      - caddy_ingress_network=kw8oo4kk80so8080o0g0cgcw
    networks:
      kw8oo4kk80so8080o0g0cgcw: null

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /app
    environment:
      VITE_API_URL: https://backend.henkify.org
      COOLIFY_BRANCH: '"master"'
      COOLIFY_CONTAINER_NAME: '"frontend-kw8oo4kk80so8080o0g0cgcw-121421738601"'
      COOLIFY_URL: 'https://collabnotes.henkify.org'
      COOLIFY_FQDN: collabnotes.henkify.org
    restart: unless-stopped
    container_name: frontend-kw8oo4kk80so8080o0g0cgcw-121421738601
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.373
      - coolify.applicationId=27
      - coolify.type=application
      - coolify.name=frontend-kw8oo4kk80so8080o0g0cgcw-121421738601
      - coolify.pullRequestId=0
      - traefik.enable=true
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.http-0-kw8oo4kk80so8080o0g0cgcw-frontend.entryPoints=http
      - traefik.http.routers.http-0-kw8oo4kk80so8080o0g0cgcw-frontend.middlewares=redirect-to-https
      - 'traefik.http.routers.http-0-kw8oo4kk80so8080o0g0cgcw-frontend.rule=Host(`collabnotes.henkify.org`) && PathPrefix(`/`)'
      - traefik.http.routers.https-0-kw8oo4kk80so8080o0g0cgcw-frontend.entryPoints=https
      - traefik.http.routers.https-0-kw8oo4kk80so8080o0g0cgcw-frontend.middlewares=gzip
      - 'traefik.http.routers.https-0-kw8oo4kk80so8080o0g0cgcw-frontend.rule=Host(`collabnotes.henkify.org`) && PathPrefix(`/`)'
      - traefik.http.routers.https-0-kw8oo4kk80so8080o0g0cgcw-frontend.tls.certresolver=letsencrypt
      - traefik.http.routers.https-0-kw8oo4kk80so8080o0g0cgcw-frontend.tls=true
      - 'caddy_0.encode=zstd gzip'
      - 'caddy_0.handle_path.0_reverse_proxy={{upstreams}}'
      - 'caddy_0.handle_path=/*'
      - caddy_0.header=-Server
      - 'caddy_0.try_files={path} /index.html /index.php'
      - 'caddy_0=https://collabnotes.henkify.org'
      - caddy_ingress_network=kw8oo4kk80so8080o0g0cgcw
    networks:
      kw8oo4kk80so8080o0g0cgcw: null
    depends_on:
      - backend

volumes: {  }
networks:
  kw8oo4kk80so8080o0g0cgcw:
    name: kw8oo4kk80so8080o0g0cgcw
    external: true
configs: {  }
secrets: {  }
